### ISSUE TITLE
Swift4 supported？

### ISSUE THREAD

**Issue by Jinkeycode** [MxABC/swiftScan#37]
would you please update this repo to supportede Swift4 & Xcode9

**Comment by zhangyuanzhi** [comment]
我用cocoapods 导入1.1.1的版本到了项目中，结果报了一大堆的错误，不能用，大神时候能够支持 Xcode9 && Swift4

**Comment by hqs5678** [comment]
本人升级的  仅供参考
https://gitee.com/hqs.com/swfit_scan_LBXScan_swift4

**Comment by zhangyuanzhi** [comment]
非常感谢

在 2017-10-16 17:40:07，"黄青松" <notifications@github.com> 写道：


本人升级的 仅供参考
https://gitee.com/hqs.com/swfit_scan_LBXScan_swift4

**Comment by MxABC** [comment]
已支持swift4.0
