### ISSUE TITLE
Disable sound when capture qrcode

### ISSUE THREAD

**Issue by Mgap** [MxABC/swiftScan#56]
Hy , 
its possible too disable sound effect after get result ?

**Comment by MxABC** [comment]
LBXScanWrapper class  init( videoPreView:UIView,objType:[AVMetadataObject.ObjectType] = [.qr],isCaptureImg:Bool,cropRect:CGRect=CGRect.zero,success:@escaping ( ([LBXScanResult]) -> Void) )    paramenter  isCaptureImg set false

**Comment by Mgap** [comment]
Ok ,
thank you so much sir

**Comment by vsp2907** [comment]
this code is not working for me, is that any other solution?
